app/models.py
from . import db
from datetime import datetime

class Subject(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True, nullable=False)
    rating = db.Column(db.Float, default=1500.0)

    def __repr__(self):
        return f"<Subject {self.name} ({self.rating})>"
    

class Match(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    winner_id = db.Column(db.Integer, db.ForeignKey('subject.id'), nullable=False)
    
class Feedback(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))    
    content = db.Column(db.Text)        

    def __repr__(self):
        return f'<Feedback {self.name}>'

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    submit = SubmitField('Proceed')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
import os
from flask_migrate import Migrate

db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__, 
                static_folder = "static",
                static_url_path="/static",
                template_folder="templates")
    
    from .routes import main_bp
    app.register_blueprint(main_bp)
    app.config['SECRET_KEY'] = os.getenv('SECRET_KEY', 'dev-secret-key')
    app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv("DATABASE_URL", 'sqlite:///subjects.db')
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app)
    migrate.init_app(app, db)
    with app.app_context():
        from . import models
    return app

app/routes.py
from flask import Blueprint, render_template, jsonify, request, session, flash, url_for, redirect
import random
from .models import Subject, Match, Feedback
from .elo import eloUpdate
from . import db
from app.forms import LoginForm
main_bp = Blueprint('main', __name__)
from datetime import datetime
import os


@main_bp.route("/rankings")
def rankings():
    subjects = Subject.query.order_by(Subject.rating.desc()).all()
    totalVotes = Match.query.count()
    return render_template("rankings.html", subjects=subjects, session=session, totalVotes=totalVotes)


@main_bp.route("/match")
def match():
    subjects = Subject.query.all()
    left, right = random.sample(subjects, 2)
    pair = [
        {"id": left.id, "name": left.name, "rating": left.rating},
        {"id": right.id, "name": right.name, "rating": right.rating}
    ]
    return jsonify({"pair": pair})

@main_bp.route("/vote", methods = ["POST"])
def vote():
    data = request.get_json()
    winner = Subject.query.get(data["winner_id"])
    loser = Subject.query.get(data["loser_id"])

    w_new, l_new = eloUpdate(winner.rating, loser.rating)
    winner.rating, loser.rating = w_new, l_new

    m = Match(
    winner_id = data["winner_id"],
    )
    db.session.add(m)
    db.session.commit()

    return jsonify({
      "winner": {"id": winner.id, "rating": winner.rating},
      "loser":  {"id": loser.id,  "rating": loser.rating}
    })

@main_bp.route('/feedback', methods=['POST'])
def feedback():
    try:
        name = session.get('username')  
        content = request.form['feedback']

        if not name or not content:
            raise ValueError("Missing username or feedback")

        fb = Feedback(name=name, content=content)
        db.session.add(fb)
        db.session.commit()
        flash("Thanks for your feedback","success")
        return redirect(url_for('main.rankings'))

    except Exception as e:
        print(f"⚠️ Feedback error: {e}")
        return "Error, please try again!", 500 

@main_bp.route('/view-feedback')
def view_feedback():
    feedbacks = Feedback.query.all()
    return render_template('view_feedback.html', feedbacks=feedbacks)


@main_bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        name = request.form.get("username", "").strip()
        if not name:
            flash("Please enter a name.", "error")
        else:
           
            session['username'] = name
            
            session['rounds_completed'] = 0
            return redirect(url_for('main.index'))
    
    return render_template("login.html")

@main_bp.route("/")
def index():
    if 'username' not in session:
        return redirect(url_for('main.login'))
    return render_template("index.html", username=session['username'])

app/templates/index.html
{% extends "layout.html" %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/script.js') }}" defer></script>
{% endblock %}

{% block content %}
      <p id="message">
         <span>Select the subject which you find <span>more difficult</span> among the pair!</span> 
        </p>
      <div class="subjects">
        <div id="S1">Physics</div>
        <div id="S2">Chemistry</div>
      </div>
      <div class="Progress">1/10</div>
      {% block styles %}
      <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
      {%endblock%}
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Subject Ranker</title>
  {% block styles %}{%endblock%}
  
  <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
</head>

<body>
  <div class="main-wrapper">
    <h1 class="title">{%block title%}SUBJECT RANKER{%endblock%}</h1>
    <div class="container">
      {%block content%} {%endblock%}
    </div>
  </div>
  {% block scripts %}{% endblock %}
  
</body>

</html>

app/templates/login.html
{% extends "layout.html" %}

{% block title %}Login{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
{% endblock %}

{% block content %}
  <h2>What’s your name?</h2>
  <form method="POST">
    <input type="text"
           name="username"
           placeholder="Enter your name"
           required
           autofocus>
    <button type="submit">Start Voting</button>
  </form>
  {% with messages = get_flashed_messages(category_filter=["error"]) %}
    {% if messages %}
      <p class="error">{{ messages[0] }}</p>
    {% endif %}
  {% endwith %}
{% endblock %}

app/templates/rankings.html
{% extends "layout.html" %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/rankings.js') }}"></script>
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/ranking.css') }}">
{% endblock %}

{% block content %}

{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <div class="flash-container">
      {% for category, message in messages %}
        <div class="flash {{ category }}">{{ message }}</div>
      {% endfor %}
    </div>
  {% endif %}
{% endwith %}

<h2 id="mess1">Subject Rankings</h2>
<br>
<p id="votes">Based on {{ totalVotes }} votes</p>
<div class="ranking">
  {% for sub in subjects %}
  <p>
    {{ sub.name }}
  </p>
  <p>
    {{ "%.2f"|format(sub.rating) }}
  </p>
  {% endfor %}
</div>
<a href="{{ url_for('main.index') }}">
  <button>Back to Vote</button>
</a>

<form method="POST" action="{{ url_for('main.feedback') }}">
  <textarea name="feedback" placeholder="Your Feedback" required></textarea>
  <button type="submit">Submit Feedback</button>
</form>

<div class="social-links">
  <a href="https://github.com/harshal-newaskar64" target="_blank">
    <img src="{{ url_for('static',filename='icons/github.png') }}" alt="GitHub">
  </a>
  <a href="https://www.linkedin.com/in/harshal-newaskar-452076335/" target="_blank">
    <img src="{{ url_for('static',filename='icons/linkedin.png') }}" alt="LinkedIn">
  </a>
</div>
{% endblock %}

app/templates/view_feedback.html
{% extends "layout.html" %}

{% block content %}
  <h2>All Feedbacks</h2>
  {% for fb in feedbacks %}
    <div>
      <h4>{{ fb.name }}</h4>
      <p>{{ fb.content }}</p>
      <hr>
    </div>
  {% endfor %}
{% endblock %}